"""
Registry of all 50 META coding interview problems.
Each entry contains metadata, source links, and references to problem/test modules.
"""

PROBLEMS = {
    1: {
        "title": "Two Sum",
        "difficulty": "Easy",
        "category": "Arrays & Hashing",
        "leetcode_num": 1,
        "source": "https://leetcode.com/problems/two-sum/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    2: {
        "title": "Move Zeroes",
        "difficulty": "Easy",
        "category": "Arrays",
        "leetcode_num": 283,
        "source": "https://leetcode.com/problems/move-zeroes/",
        "ref": "https://www.designgurus.io/blog/top-20-coding-questions-to-pass-meta-interview",
    },
    3: {
        "title": "Valid Palindrome",
        "difficulty": "Easy",
        "category": "Strings",
        "leetcode_num": 125,
        "source": "https://leetcode.com/problems/valid-palindrome/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    4: {
        "title": "Best Time to Buy and Sell Stock",
        "difficulty": "Easy",
        "category": "Arrays & DP",
        "leetcode_num": 121,
        "source": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    5: {
        "title": "Valid Parentheses",
        "difficulty": "Easy",
        "category": "Stacks",
        "leetcode_num": 20,
        "source": "https://leetcode.com/problems/valid-parentheses/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    6: {
        "title": "Merge Sorted Array",
        "difficulty": "Easy",
        "category": "Arrays",
        "leetcode_num": 88,
        "source": "https://leetcode.com/problems/merge-sorted-array/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    7: {
        "title": "Reverse Linked List",
        "difficulty": "Easy",
        "category": "Linked Lists",
        "leetcode_num": 206,
        "source": "https://leetcode.com/problems/reverse-linked-list/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    8: {
        "title": "Number of Islands",
        "difficulty": "Medium",
        "category": "Graphs",
        "leetcode_num": 200,
        "source": "https://leetcode.com/problems/number-of-islands/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    9: {
        "title": "Palindrome Linked List",
        "difficulty": "Easy",
        "category": "Linked Lists",
        "leetcode_num": 234,
        "source": "https://leetcode.com/problems/palindrome-linked-list/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    10: {
        "title": "Product of Array Except Self",
        "difficulty": "Medium",
        "category": "Arrays",
        "leetcode_num": 238,
        "source": "https://leetcode.com/problems/product-of-array-except-self/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    11: {
        "title": "3Sum",
        "difficulty": "Medium",
        "category": "Arrays",
        "leetcode_num": 15,
        "source": "https://leetcode.com/problems/3sum/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    12: {
        "title": "Merge Intervals",
        "difficulty": "Medium",
        "category": "Arrays & Sorting",
        "leetcode_num": 56,
        "source": "https://leetcode.com/problems/merge-intervals/",
        "ref": "https://www.educative.io/blog/cracking-top-facebook-coding-interview-questions",
    },
    13: {
        "title": "Group Anagrams",
        "difficulty": "Medium",
        "category": "Strings & Hashing",
        "leetcode_num": 49,
        "source": "https://leetcode.com/problems/group-anagrams/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    14: {
        "title": "Binary Tree Level Order Traversal",
        "difficulty": "Medium",
        "category": "Trees",
        "leetcode_num": 102,
        "source": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
        "ref": "https://www.educative.io/blog/cracking-top-facebook-coding-interview-questions",
    },
    15: {
        "title": "Clone Graph",
        "difficulty": "Medium",
        "category": "Graphs",
        "leetcode_num": 133,
        "source": "https://leetcode.com/problems/clone-graph/",
        "ref": "https://www.educative.io/blog/cracking-top-facebook-coding-interview-questions",
    },
    16: {
        "title": "Word Break",
        "difficulty": "Medium",
        "category": "Dynamic Programming",
        "leetcode_num": 139,
        "source": "https://leetcode.com/problems/word-break/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    17: {
        "title": "LRU Cache",
        "difficulty": "Medium",
        "category": "Design",
        "leetcode_num": 146,
        "source": "https://leetcode.com/problems/lru-cache/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    18: {
        "title": "Validate Binary Search Tree",
        "difficulty": "Medium",
        "category": "Trees",
        "leetcode_num": 98,
        "source": "https://leetcode.com/problems/validate-binary-search-tree/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    19: {
        "title": "Lowest Common Ancestor of a Binary Tree",
        "difficulty": "Medium",
        "category": "Trees",
        "leetcode_num": 236,
        "source": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    20: {
        "title": "Subsets",
        "difficulty": "Medium",
        "category": "Backtracking",
        "leetcode_num": 78,
        "source": "https://leetcode.com/problems/subsets/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    21: {
        "title": "Search in Rotated Sorted Array",
        "difficulty": "Medium",
        "category": "Binary Search",
        "leetcode_num": 33,
        "source": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
        "ref": "https://www.educative.io/blog/cracking-top-facebook-coding-interview-questions",
    },
    22: {
        "title": "Kth Largest Element in an Array",
        "difficulty": "Medium",
        "category": "Sorting & Heaps",
        "leetcode_num": 215,
        "source": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    23: {
        "title": "Letter Combinations of a Phone Number",
        "difficulty": "Medium",
        "category": "Backtracking",
        "leetcode_num": 17,
        "source": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    24: {
        "title": "Sort Colors",
        "difficulty": "Medium",
        "category": "Arrays & Sorting",
        "leetcode_num": 75,
        "source": "https://leetcode.com/problems/sort-colors/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    25: {
        "title": "Decode Ways",
        "difficulty": "Medium",
        "category": "Dynamic Programming",
        "leetcode_num": 91,
        "source": "https://leetcode.com/problems/decode-ways/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    26: {
        "title": "Implement Trie (Prefix Tree)",
        "difficulty": "Medium",
        "category": "Trees & Design",
        "leetcode_num": 208,
        "source": "https://leetcode.com/problems/implement-trie-prefix-tree/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    27: {
        "title": "Course Schedule II",
        "difficulty": "Medium",
        "category": "Graphs",
        "leetcode_num": 210,
        "source": "https://leetcode.com/problems/course-schedule-ii/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    28: {
        "title": "Word Search",
        "difficulty": "Medium",
        "category": "Backtracking & Matrix",
        "leetcode_num": 79,
        "source": "https://leetcode.com/problems/word-search/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    29: {
        "title": "Diagonal Traverse",
        "difficulty": "Medium",
        "category": "Matrix",
        "leetcode_num": 498,
        "source": "https://leetcode.com/problems/diagonal-traverse/",
        "ref": "https://www.designgurus.io/blog/top-20-coding-questions-to-pass-meta-interview",
    },
    30: {
        "title": "Maximum Swap",
        "difficulty": "Medium",
        "category": "Math & Greedy",
        "leetcode_num": 670,
        "source": "https://leetcode.com/problems/maximum-swap/",
        "ref": "https://www.designgurus.io/blog/top-20-coding-questions-to-pass-meta-interview",
    },
    31: {
        "title": "Custom Sort String",
        "difficulty": "Medium",
        "category": "Strings & Sorting",
        "leetcode_num": 791,
        "source": "https://leetcode.com/problems/custom-sort-string/",
        "ref": "https://www.designgurus.io/blog/top-20-coding-questions-to-pass-meta-interview",
    },
    32: {
        "title": "Basic Calculator II",
        "difficulty": "Medium",
        "category": "Stacks & Math",
        "leetcode_num": 227,
        "source": "https://leetcode.com/problems/basic-calculator-ii/",
        "ref": "https://www.designgurus.io/blog/top-20-coding-questions-to-pass-meta-interview",
    },
    33: {
        "title": "Minimum Window Substring",
        "difficulty": "Hard",
        "category": "Strings & Sliding Window",
        "leetcode_num": 76,
        "source": "https://leetcode.com/problems/minimum-window-substring/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    34: {
        "title": "Merge K Sorted Lists",
        "difficulty": "Hard",
        "category": "Linked Lists & Heaps",
        "leetcode_num": 23,
        "source": "https://leetcode.com/problems/merge-k-sorted-lists/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    35: {
        "title": "Serialize and Deserialize Binary Tree",
        "difficulty": "Hard",
        "category": "Trees & Design",
        "leetcode_num": 297,
        "source": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
        "ref": "https://www.designgurus.io/blog/top-20-coding-questions-to-pass-meta-interview",
    },
    36: {
        "title": "Trapping Rain Water",
        "difficulty": "Hard",
        "category": "Arrays & Two Pointers",
        "leetcode_num": 42,
        "source": "https://leetcode.com/problems/trapping-rain-water/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    37: {
        "title": "Longest Consecutive Sequence",
        "difficulty": "Medium",
        "category": "Arrays & Hashing",
        "leetcode_num": 128,
        "source": "https://leetcode.com/problems/longest-consecutive-sequence/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    38: {
        "title": "Add Binary",
        "difficulty": "Easy",
        "category": "Strings & Math",
        "leetcode_num": 67,
        "source": "https://leetcode.com/problems/add-binary/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    39: {
        "title": "Pow(x, n)",
        "difficulty": "Medium",
        "category": "Math & Recursion",
        "leetcode_num": 50,
        "source": "https://leetcode.com/problems/powx-n/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    40: {
        "title": "Next Permutation",
        "difficulty": "Medium",
        "category": "Arrays",
        "leetcode_num": 31,
        "source": "https://leetcode.com/problems/next-permutation/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    41: {
        "title": "Maximal Rectangle",
        "difficulty": "Hard",
        "category": "Stacks & DP",
        "leetcode_num": 85,
        "source": "https://leetcode.com/problems/maximal-rectangle/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    42: {
        "title": "Maximal Square",
        "difficulty": "Medium",
        "category": "Dynamic Programming",
        "leetcode_num": 221,
        "source": "https://leetcode.com/problems/maximal-square/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    43: {
        "title": "Remove Invalid Parentheses",
        "difficulty": "Hard",
        "category": "BFS & Backtracking",
        "leetcode_num": 301,
        "source": "https://leetcode.com/problems/remove-invalid-parentheses/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    44: {
        "title": "Expression Add Operators",
        "difficulty": "Hard",
        "category": "Backtracking & Math",
        "leetcode_num": 282,
        "source": "https://leetcode.com/problems/expression-add-operators/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    45: {
        "title": "Integer to English Words",
        "difficulty": "Hard",
        "category": "Strings & Math",
        "leetcode_num": 273,
        "source": "https://leetcode.com/problems/integer-to-english-words/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    46: {
        "title": "Minimum Size Subarray Sum",
        "difficulty": "Medium",
        "category": "Sliding Window",
        "leetcode_num": 209,
        "source": "https://leetcode.com/problems/minimum-size-subarray-sum/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    47: {
        "title": "Diameter of Binary Tree",
        "difficulty": "Easy",
        "category": "Trees",
        "leetcode_num": 543,
        "source": "https://leetcode.com/problems/diameter-of-binary-tree/",
        "ref": "https://www.designgurus.io/blog/top-20-coding-questions-to-pass-meta-interview",
    },
    48: {
        "title": "Longest Increasing Subsequence",
        "difficulty": "Medium",
        "category": "Dynamic Programming",
        "leetcode_num": 300,
        "source": "https://leetcode.com/problems/longest-increasing-subsequence/",
        "ref": "https://www.geeksforgeeks.org/dsa/facebookmeta-sde-sheet-interview-questions-and-answers/",
    },
    49: {
        "title": "Multiply Strings",
        "difficulty": "Medium",
        "category": "Strings & Math",
        "leetcode_num": 43,
        "source": "https://leetcode.com/problems/multiply-strings/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
    50: {
        "title": "Simplify Path",
        "difficulty": "Medium",
        "category": "Strings & Stacks",
        "leetcode_num": 71,
        "source": "https://leetcode.com/problems/simplify-path/",
        "ref": "https://gist.github.com/fielding/8e22a9e8c2eb4c707f10d3a2b5db59c7",
    },
}


def get_problem(problem_id):
    return PROBLEMS.get(problem_id)


def get_all_problems():
    return PROBLEMS


def get_problems_by_difficulty(difficulty):
    return {k: v for k, v in PROBLEMS.items() if v["difficulty"].lower() == difficulty.lower()}


def get_problems_by_category(category):
    return {k: v for k, v in PROBLEMS.items() if category.lower() in v["category"].lower()}
